### ISSUE TITLE
Load Grub2 with UEFI

### ISSUE THREAD

**Issue by ruky87** [niemtin007/Multiboot-Toolkit#13]
I created the Multiboot drive and it's working with standard boot, showing the grub2 menu. But With UEFI the Windows Boot Manager is shown, how can I switch to grub2 also in UEFI?

**Comment by niemtin007** [comment]
Hi there,

The reason is you activate the "Create EFI Partition for Secure Boot". This option will create a Window EFI Partition in the first disk, and another bootloader (Grub2) in the second partition.

![Capture](https://user-images.githubusercontent.com/12592676/85206916-86963280-b34f-11ea-93b7-75632a2f4829.PNG)

In many Firmware Interface, It prioritizes bootloader booting in the first partition. So this is why you always see the Windows Boot Manager as the default bootloader. Other devices, sometimes it has an option to allow you to select the bootloader first directly via the menu or let you choose the boot*.efi to run bootloader manually.

If you don't like this default behavior you can change the priority of bootloader by using the " Set Default Boot (UEFI)" feature. Then choose the grub2 as a default bootloader.

![Capture](https://user-images.githubusercontent.com/12592676/85207188-433cc380-b351-11ea-9584-752d22e9c25f.PNG)

niemtin007,
